"""
Purpose:
Combine rule-based detection issues with user-facing explanations.
This service prepares frontend-ready cleaning suggestions.
It does not clean data.
It does not modify original datasets.
"""

from app.services.llm_service import generate_explanations


def build_suggestions_from_issues(issues: list) -> tuple[list, dict]:
    """
    Converts rule-based issue objects into frontend-ready suggestion objects.

    Args:
        issues: list of issue dictionaries generated by detection rules

    Returns:
        Tuple of (suggestions list, llm_metadata dict)
    """
    explanations, llm_meta = generate_explanations(issues)

    suggestions = []
    for index, (issue, explanation_data) in enumerate(zip(issues, explanations), start=1):
        suggestion = {
            "suggestion_id": f"suggestion_{index}",
            "issue_id": issue.get("issue_id"),
            "column": issue.get("column"),
            "issue_type": issue.get("issue_type"),
            "severity": issue.get("severity"),
            "suggested_action": issue.get("suggested_action"),
            "reason_code": issue.get("reason_code"),
            "metrics": issue.get("metrics", {}),
            "explanation": explanation_data.get("explanation"),
            "recommendation_reason": explanation_data.get("recommendation_reason"),
            "user_warning": explanation_data.get("user_warning"),
            "requires_user_approval": True,
            "status": "pending"
        }
        suggestions.append(suggestion)

    return suggestions, llm_meta